[build.environment]
  # Mirror Netlify’s Auth0 extension vars into Vite’s client‐exposed VITE_ namespace
  VITE_AUTH0_DOMAIN    = "$AUTH0_DOMAIN"
  VITE_AUTH0_CLIENT_ID = "$AUTH0_CLIENT_ID"
  VITE_AUTH0_AUDIENCE  = "$AUTH0_AUDIENCE"